version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
nuget:
  project_feed: true
before_build:
- cmd: nuget restore Source\scrape-x.sln
build:
  project: Source\scrape-x.sln
  verbosity: minimal
after_build:
- cmd: >-
    dotnet tool install --global dotnet-sonarscanner

    dotnet sonarscanner begin /k:"alexleen_scrape-x" /d:sonar.organization="alexleen-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="ece6946878045182999e7fc3429462861816aed6" /d:sonar.cs.opencover.reportsPaths=".\coverage.xml"

    dotnet build Source\scrape-x.sln -c Release

    nuget install OpenCover -Version 4.6.831-rc -Source https://www.myget.org/F/opencover/api/v3/index.json

    OpenCover.4.6.831\tools\OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test -c Release Source\ScrapeX.Test\ScrapeX.Test.csproj" -filter:"+[*]* -[nunit*]* -[ScrapeX.Test]*" -output:".\coverage.xml" -returntargetcode -oldStyle

    dotnet sonarscanner end /d:sonar.login="ece6946878045182999e7fc3429462861816aed6"
test_script:
- cmd: >-
    nuget install OpenCover -Version 4.6.831-rc -Source https://www.myget.org/F/opencover/api/v3/index.json

    nuget install Codecov -Version 1.1.0

    OpenCover.4.6.831\tools\OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:"test -c Release Source\ScrapeX.Test\ScrapeX.Test.csproj" -filter:"+[*]* -[nunit*]* -[ScrapeX.Test]*" -output:".\coverage.xml" -returntargetcode -oldStyle

    Codecov.1.1.0\tools\codecov.exe -f ".\coverage.xml"
artifacts:
- path: .\coverage.xml
  name: Coverage
- path: Source\ScrapeX\bin\Release\ScrapeX*.nupkg
  name: Package
deploy:
  provider: NuGet
  api_key:
    secure: ClqMqfuX+jJtN/3mf7YMuYk1JJ4PkHYFuTzsQ9O4oc9qmR1RQa9CaOnhREli73qZ
  on:
    branch: master
    APPVEYOR_REPO_TAG: true